"""
Negative corpus: synthetic bug-class exemplars + provenance-backed advisory
regressions (roadmap issue #9; provenance split per deep-review F-02).

Two provenance categories - never mix them:

1. Synthetic bug-class exemplars (generated + verified fixtures)
   Name:  synthetic-<bug-class>-<slug>.gguf
   Hand-built malformed inputs that exercise a specific bug class (parse /
   int-overflow / dims / types / alloc / metadata). They are NOT
   reproductions of any specific CVE/advisory and must not carry an advisory
   identity; `source` states the mechanism only.

2. True advisory regressions (promoted after triage; generated + verified)
   Name:  cve-YYYY-NNNN[-slug].gguf
   A fixture may use a cve-* name only once it has a verifiable primary
   source: `cve`, `source_url`, `ghsa` and a patched reference recorded in
   the CASES entry plus the fixture `sha256` (REQUIRED_CVE_FIELDS, enforced
   by _require_triaged_provenance and checked against the generated bytes).
   Promoted cases also carry `fixture_origin` from a closed vocabulary:
   "exact-poc" when the fixture reproduces the advisory's own proof of
   concept, "advisory-derived" when it follows the advisory's
   mechanism/example shape, or "mechanism-equivalent" when SafeGGUF proves
   only the equivalent admission property and does not reproduce the
   upstream allocation byte-for-byte (stated in `source`).
   Version/commit provenance is nullable: `affected_range`,
   `affected_version`, `patched_version` and `patched_commit` stay null
   where no verifiable value was recorded - null means unknown, and no
   range, URL or SHA is ever invented. Advisory entries whose provenance is
   still un-triaged stay in ADVISORY_PLACEHOLDERS as manifest-only records
   (fixture: null, provenance fields TRIAGE-PENDING) and are neither
   generated nor verified. Promote a placeholder to a real cve-* fixture
   only after triage.

Per-case comment convention (the CASES registry is the committed record;
tests/fixtures/negative/manifest.json is the regenerated snapshot):

  fixture_type       synthetic-class-exemplar | advisory-regression.
  fixture_origin     Closed vocabulary on promoted cve-* cases: exact-poc |
                     advisory-derived | mechanism-equivalent; None for
                     synthetic exemplars.
  cve                CVE identifier on promoted cve-* cases (must agree with
                     the fixture name); None for synthetic exemplars.
  ghsa               GHSA advisory identifier on promoted cve-* cases; None
                     for synthetic exemplars.
  source             Mechanism description for synthetic cases; primary
                     advisory reference for triaged advisory cases.
  source_url         Verifiable primary source URL (https://); None for
                     synthetic cases (no advisory exists), TRIAGE-PENDING for
                     placeholders.
  affected_range     Upstream affected version/commit range, or null when the
                     triage did not verify one.
  affected_version   Upstream affected version, or null when unverified.
  patched_version    Upstream version containing the fix, or null when no
                     version was recorded.
  patched_commit     Upstream commit containing the fix, or null when unknown.
                     cve-* cases must record at least one patched reference
                     (patched_version or patched_commit).
  expected_profile   Profile the rejection is asserted under (gguf-spec |
                     llama-cpp); must match the --profile in cli_args.
  sha256             Committed fixture hash on cve-* cases (must match the
                     generated bytes); synthetic cases record it in the
                     manifest only.
  expected_behavior  What SafeGGUF must do: exit 2 (REJECT) and the expected
                     error_code surfaced on stderr / JSON.

All cases and fixtures are behavior-referenced against the pinned upstream in
UPSTREAM_REF (ggml 0.23.0 e91ded11...) and the manifest records that pin
top-level as `upstream_behavior_reference`.

Generation is fully deterministic: fixed little-endian bytes, no randomness,
no timestamps, sorted manifest keys. Re-running overwrites the fixture
directory contents (stale *.gguf files not in CASES are pruned).

Run:  python tests/negative_corpus.py            # generate + verify
      python tests/negative_corpus.py --generate-only
      python tests/negative_corpus.py --verify-only
Verification needs the ReleaseSafe binary at zig-out/bin/safegguf
(zig build -Doptimize=ReleaseSafe). Exit 0 = all cases generated and all
rejections hold; exit 1 = generation or verification failed.
"""

import argparse
import hashlib
import json
import os
import re
import struct
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
SAFEGGUF_BIN = os.path.join(REPO_ROOT, "zig-out", "bin", "safegguf")
NEGATIVE_DIR = os.path.join(SCRIPT_DIR, "fixtures", "negative")

BUG_CLASSES = ("parse", "int-overflow", "dims", "types", "alloc", "metadata")

UPSTREAM_REF = "pinned ggml 0.23.0 e91ded11bdcd78c42f9c8d3978ff6686eb4c1226"

# Documented null policy (B3) for the nullable version/commit provenance on
# cve-* cases: the verified advisory provenance records the patched commit
# only - no affected range/version and no patched version was verified - so
# `affected_range`, `affected_version` and `patched_version` stay null. null
# means "not verified / unknown" and is never replaced by a sentinel string
# or an invented range/SHA; the guard requires a triaged value only for the
# fields that are genuinely mandatory (advisory identity, primary source,
# fixture hash, expected profile/error) and requires at least one patched
# reference (patched_version or patched_commit).
FIXTURE_ORIGINS = ("exact-poc", "advisory-derived", "mechanism-equivalent")

# Profiles the CLI accepts; the effective --profile of a case must name one
# of them and must match the case's expected_profile.
PROFILES = ("gguf-spec", "llama-cpp")

CVE_ID_RE = re.compile(r"^CVE-\d{4}-\d{4,}$")
GHSA_ID_RE = re.compile(r"^GHSA-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


def align_up(val, align):
    rem = val % align
    return val if rem == 0 else val + (align - rem)


def _pad_to_alignment(payload, alignment=32):
    # Append deterministic zero alignment padding up to the tensor-data base
    # (GGUF default alignment 32; no general.alignment key is emitted) so the
    # fixture is a complete GGUF file apart from the targeted arithmetic
    # defect.
    return payload + b"\x00" * (align_up(len(payload), alignment) - len(payload))


def _header(tensor_count, kv_count):
    b = bytearray(b"GGUF")
    b += struct.pack("<I", 3)
    b += struct.pack("<Q", tensor_count)
    b += struct.pack("<Q", kv_count)
    return b


def _kv_string(key, val):
    b = bytearray()
    b += struct.pack("<Q", len(key))
    b += key
    b += struct.pack("<I", 8)  # GGUF_METADATA_VALUE_TYPE_STRING
    b += struct.pack("<Q", len(val))
    b += val
    return b


def _tensor_desc(name, n_dims, dims, tensor_type, offset):
    b = bytearray()
    b += struct.pack("<Q", len(name))
    b += name
    b += struct.pack("<I", n_dims)
    for d in dims:
        b += struct.pack("<Q", d)
    b += struct.pack("<I", tensor_type)
    b += struct.pack("<Q", offset)
    return b


def build_parse_string_past_eof():
    # Metadata string value declares 60000 bytes (under the 65536 string cap
    # so the limit check does not fire first) while only 8 bytes remain in
    # the file: the read would extend past EOF.
    b = _header(0, 1)
    b += struct.pack("<Q", len(b"general.name"))
    b += b"general.name"
    b += struct.pack("<I", 8)  # STRING
    b += struct.pack("<Q", 60000)  # declared length >> remaining bytes
    b += b"\x00" * 8
    return b


def build_parse_truncated_tensor_descriptor():
    # Header declares 2 tensors; only the first descriptor is present and the
    # second one is cut off right after its name.
    b = _header(2, 0)
    b += _tensor_desc(b"t0", 1, [8], 0, 0)
    b += struct.pack("<Q", 2)  # name_len of t1, then EOF mid-descriptor
    b += b"t1"
    return b


def build_int_overflow_dims_product():
    # dims [2^63, 2]: each dim fits u64 but the element-count product wraps
    # u64 exactly (2^64).
    return _header(1, 0) + _tensor_desc(b"ovf_dims", 2, [0x8000000000000000, 2], 0, 0)


def build_int_overflow_nbytes():
    # dims [2^62, 1]: the element count fits u64, but nbytes = 2^62 x 4
    # (F32) wraps u64 exactly.
    return _header(1, 0) + _tensor_desc(b"ovf_bytes", 2, [0x4000000000000000, 1], 0, 0)


def build_dims_ndims_5():
    # n_dims = 5 exceeds the GGUF v3 maximum of 4.
    return _header(1, 0) + _tensor_desc(b"five_dims", 5, [1, 1, 1, 1, 1], 0, 0)


def build_dims_uint32_max():
    # n_dims = UINT32_MAX: dim-count field abuse; the dims array would claim
    # 4 GiB of u64 dimension values from a ~30-byte file.
    return _header(1, 0) + _tensor_desc(b"max_dims", 0xFFFFFFFF, [], 0, 0)


def build_types_invalid_tensor_type_43():
    # Tensor type 43 is the first id beyond the pinned 43-slot GGML table
    # (e91ded11); ids >= 43 must be rejected, never coerced to a layout.
    return _header(1, 0) + _tensor_desc(b"type43", 1, [8], 43, 0)


def build_types_metadata_value_type_99():
    # Metadata value type 99 exceeds the valid GGUF metadata type range
    # (0..12): type-confusion class.
    b = _header(0, 1)
    b += struct.pack("<Q", len(b"general.bad_type"))
    b += b"general.bad_type"
    b += struct.pack("<I", 99)  # invalid value type
    b += b"\x00" * 8
    return b


def build_alloc_kv_count_dos():
    # n_kv = UINT64_MAX: declared count implies ~1.8e19 KV entries (min 13
    # bytes each) from a 24-byte file; must hit the entry-count limit before
    # any allocation is attempted.
    return _header(0, 0xFFFFFFFFFFFFFFFF)


def build_alloc_key_string_len_dos():
    # Key length 0xFFFFFFFF (4 GiB) from a 32-byte file; must hit the 65536
    # string cap before allocation.
    b = _header(0, 1)
    b += struct.pack("<Q", 0xFFFFFFFF)
    b += b"K" * 16
    return b


def build_metadata_invalid_utf8_value():
    # String value 0xFF 0xFE 0xFD 0xFA is not valid UTF-8; strings are
    # attacker-controlled scan targets, not opaque bytes.
    return _header(0, 1) + _kv_string(b"general.name", b"\xff\xfe\xfd\xfa")


def build_metadata_array_count_dos():
    # Fixed-size I32 array declaring 10,000,001 elements (one over the 10M
    # array cap) from a ~40-byte file.
    b = _header(0, 1)
    b += struct.pack("<Q", len(b"general.arr"))
    b += b"general.arr"
    b += struct.pack("<I", 9)  # ARRAY
    b += struct.pack("<I", 4)  # element type INT32
    b += struct.pack("<Q", 10_000_001)
    b += b"\x00" * 8
    return b


def build_cve_2025_53630_cumulative_overflow():
    # CVE-2025-53630 / GHSA-vgg9-87g3-85w8, fixed by
    # 26a48ad699d50b6268900062661bd22f3e792579 (upstream #14595 "prevent
    # integer overflow in gguf tensor size calculation"). Each tensor is
    # individually valid (F32 [2^61, 1] -> 2^63 bytes, below UINT64_MAX), but
    # the aligned cumulative addition 2^63 + 2^63 wraps u64. That cumulative
    # sum is computed only in the llama.cpp contiguity path (checkedAlignUp
    # over descriptor-ordered tensors + checkedAdd), so the case pins
    # --profile llama-cpp; the gguf-spec profile validates per-tensor ends
    # instead of a cumulative layout sum.
    b = _header(2, 0)
    b += _tensor_desc(b"cve-2025-53630-cumulative-0", 2, [0x2000000000000000, 1], 0, 0)
    b += _tensor_desc(
        b"cve-2025-53630-cumulative-1", 2, [0x2000000000000000, 1], 0, 0x8000000000000000
    )
    return _pad_to_alignment(b)


def build_cve_2026_27940_final_size_overflow():
    # CVE-2026-27940 / GHSA-3p4r-fq3f-q74v, fixed by
    # 418dea39cea85d3496c8b04a118c3b17f3940ad8 (advisory build b8146): bypass
    # of the CVE-2025-53630 fix via the final context memory-size arithmetic.
    # Mechanism-equivalent fixture: the per-tensor size and the cumulative
    # aligned layout are representable (F32 [2^62 - 8, 1] -> 2^64 - 32
    # bytes), but the final tensor-data end (tensor_data_base + cumulative
    # size, checkedAdd in the llama.cpp contiguity path) is not. SafeGGUF
    # rejects at admission, before any downstream ggml context allocation; it
    # does not reproduce the upstream heap allocation byte-for-byte.
    b = _header(1, 0)
    b += _tensor_desc(b"cve-2026-27940-memsize", 2, [0x3FFFFFFFFFFFFFF8, 1], 0, 0)
    return _pad_to_alignment(b)


def build_cve_2026_33298_nbytes_overflow():
    # CVE-2026-33298 / GHSA-96jg-mvhq-q7q7, fixed by
    # 4e5b83b226919c146fbfa754641a6772bcb2d722 (upstream #19072 "check that
    # tensor size is representable"; advisory build b7824). Flagship
    # advisory-derived shape F32 [1024, 1024, 2^42 + 1, 1]: the element
    # product 2^62 + 2^20 fits u64, but the byte multiplication
    # (x4 = 2^64 + 2^22) wraps u64. Renamed from
    # synthetic-int-overflow-flagship-nbytes.gguf at promotion; payload
    # unchanged.
    return _header(1, 0) + _tensor_desc(
        b"ovf_flagship", 4, [1024, 1024, 0x400000000001, 1], 0, 0
    )


CASES = [
    {
        "name": "synthetic-parse-metadata-string-past-eof.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "parse",
        "build": build_parse_string_past_eof,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): metadata "
            "string value declares 60000 bytes while only 8 bytes remain in "
            "the file; exercises the string-length / EOF-boundary class."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_UnexpectedEof): declared "
            "string length extends past end of file; fail closed instead of "
            "reading out of bounds."
        ),
        "expected_error_code": "E_UnexpectedEof",
        "cli_args": [],
    },
    {
        "name": "synthetic-parse-truncated-tensor-descriptor.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "parse",
        "build": build_parse_truncated_tensor_descriptor,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): parser "
            "trusts the declared tensor count and reads a descriptor table "
            "that is truncated mid-entry."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_UnexpectedEof): tensor "
            "descriptor table extends past end of file."
        ),
        "expected_error_code": "E_UnexpectedEof",
        "cli_args": [],
    },
    {
        "name": "synthetic-int-overflow-dims-product.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "int-overflow",
        "build": build_int_overflow_dims_product,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "element-count product overflow in the tensor path; dims "
            "[2^63, 2] wrap u64."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ArithmeticOverflow): "
            "element-count product 2^64 overflows u64 under checked arithmetic."
        ),
        "expected_error_code": "E_ArithmeticOverflow",
        "cli_args": [],
    },
    {
        "name": "synthetic-int-overflow-nbytes.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "int-overflow",
        "build": build_int_overflow_nbytes,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "byte-size multiplication overflow; elements fit u64 (2^62) but "
            "nbytes = 2^62 x 4 wraps u64."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ArithmeticOverflow): "
            "byte-size computation overflows u64 under checked arithmetic."
        ),
        "expected_error_code": "E_ArithmeticOverflow",
        "cli_args": [],
    },
    {
        "name": "synthetic-dims-ndims-5.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "dims",
        "build": build_dims_ndims_5,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "dimension-count field above the GGUF v3 maximum of 4."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_InvalidDimensionCount): "
            "n_dims 5 > 4."
        ),
        "expected_error_code": "E_InvalidDimensionCount",
        "cli_args": [],
    },
    {
        "name": "synthetic-dims-uint32-max.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "dims",
        "build": build_dims_uint32_max,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "dim-count field set to UINT32_MAX, claiming a 4 GiB dimension "
            "array from a ~30-byte file."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_InvalidDimensionCount): "
            "n_dims 0xFFFFFFFF > 4."
        ),
        "expected_error_code": "E_InvalidDimensionCount",
        "cli_args": [],
    },
    {
        "name": "synthetic-types-invalid-tensor-type-43.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "types",
        "build": build_types_invalid_tensor_type_43,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): tensor "
            "type id 43, beyond the pinned 43-slot GGML table, must never be "
            "coerced to a layout."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_InvalidTensorType): "
            "tensor type ids >= 43 are rejected."
        ),
        "expected_error_code": "E_InvalidTensorType",
        "cli_args": [],
    },
    {
        "name": "synthetic-types-metadata-value-type-99.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "types",
        "build": build_types_metadata_value_type_99,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "metadata value type id outside the valid GGUF range (0..12), "
            "type-confusion class."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_InvalidMetadataType): "
            "value type 99 > 12."
        ),
        "expected_error_code": "E_InvalidMetadataType",
        "cli_args": [],
    },
    {
        "name": "synthetic-alloc-kv-count-dos.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "alloc",
        "build": build_alloc_kv_count_dos,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "allocation-DoS class - header declares UINT64_MAX metadata "
            "entries; parsers that allocate per declared count before "
            "validating exhaust memory."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ResourceLimitExceeded): "
            "n_kv exceeds the 1,000,000-entry limit before any allocation."
        ),
        "expected_error_code": "E_ResourceLimitExceeded",
        "cli_args": [],
    },
    {
        "name": "synthetic-alloc-key-string-len-dos.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "alloc",
        "build": build_alloc_key_string_len_dos,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): "
            "allocation-DoS class - key length 0xFFFFFFFF (4 GiB) declared "
            "from a 32-byte file."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ResourceLimitExceeded): "
            "key length exceeds the 65536-byte string cap."
        ),
        "expected_error_code": "E_ResourceLimitExceeded",
        "cli_args": [],
    },
    {
        "name": "synthetic-metadata-invalid-utf8-value.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "metadata",
        "build": build_metadata_invalid_utf8_value,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): metadata "
            "class - string value 0xFF 0xFE 0xFD 0xFA is not valid UTF-8."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_InvalidUtf8): string "
            "values must be valid UTF-8."
        ),
        "expected_error_code": "E_InvalidUtf8",
        "cli_args": [],
    },
    {
        "name": "synthetic-metadata-array-count-dos.gguf",
        "fixture_type": "synthetic-class-exemplar",
        "bug_class": "metadata",
        "build": build_metadata_array_count_dos,
        "source": (
            "Synthetic bug-class exemplar (no advisory provenance): metadata "
            "class - fixed-size I32 array declares 10,000,001 elements, one "
            "over the 10M array cap."
        ),
        "source_url": None,
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": None,
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ResourceLimitExceeded): "
            "array element count exceeds the 10,000,000 limit."
        ),
        "expected_error_code": "E_ResourceLimitExceeded",
        "cli_args": [],
    },
    # Promoted advisory regressions (provenance triaged from verifiable
    # primary sources; the un-triaged registry is ADVISORY_PLACEHOLDERS).
    {
        "name": "cve-2025-53630-cumulative-overflow.gguf",
        "fixture_type": "advisory-regression",
        "fixture_origin": "advisory-derived",
        "cve": "CVE-2025-53630",
        "ghsa": "GHSA-vgg9-87g3-85w8",
        "bug_class": "int-overflow",
        "build": build_cve_2025_53630_cumulative_overflow,
        "source": (
            "Advisory regression (CVE-2025-53630 / GHSA-vgg9-87g3-85w8; fix "
            "26a48ad699d50b6268900062661bd22f3e792579, upstream #14595): "
            "cumulative tensor-data-size overflow. Advisory-derived: two F32 "
            "[2^61, 1] tensors that are individually valid (2^63 bytes each); "
            "the fixture is built to the advisory's cumulative-size mechanism, "
            "not copied from upstream. Pinned to --profile llama-cpp because "
            "only that profile computes the cumulative descriptor-ordered "
            "layout sum that overflows."
        ),
        "source_url": (
            "https://github.com/ggml-org/llama.cpp/security/advisories/"
            "GHSA-vgg9-87g3-85w8"
        ),
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": "26a48ad699d50b6268900062661bd22f3e792579",
        "sha256": "e33b25937bbdd5e12d64bdeaaf02f9b590976f1296b05cc572f3a502d3ebbc10",
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ArithmeticOverflow, "
            "category arithmetic): the aligned cumulative addition "
            "2^63 + 2^63 wraps u64 in the llama.cpp contiguity check while "
            "individual tensor byte sizes stay valid."
        ),
        "expected_profile": "llama-cpp",
        "expected_error_code": "E_ArithmeticOverflow",
        "cli_args": ["--profile", "llama-cpp"],
    },
    {
        "name": "cve-2026-27940-memsize-overflow.gguf",
        "fixture_type": "advisory-regression",
        "fixture_origin": "mechanism-equivalent",
        "cve": "CVE-2026-27940",
        "ghsa": "GHSA-3p4r-fq3f-q74v",
        "bug_class": "int-overflow",
        "build": build_cve_2026_27940_final_size_overflow,
        "source": (
            "Advisory regression (CVE-2026-27940 / GHSA-3p4r-fq3f-q74v; fix "
            "418dea39cea85d3496c8b04a118c3b17f3940ad8, advisory build b8146): "
            "bypass of the CVE-2025-53630 fix via the final context memory-size "
            "arithmetic. Mechanism-equivalent, not a byte-for-byte "
            "reproduction: SafeGGUF does not perform the downstream ggml "
            "context allocation, so the fixture proves the equivalent "
            "admission property - the per-tensor size and the cumulative "
            "aligned layout are representable (F32 [2^62 - 8, 1] -> 2^64 - 32 "
            "bytes), but the final tensor-data end (tensor_data_base + "
            "cumulative size) is not - and SafeGGUF rejects before any "
            "downstream allocation. cli_args pin --profile llama-cpp, the "
            "profile whose loader computes the cumulative/final layout sum."
        ),
        "source_url": (
            "https://github.com/ggml-org/llama.cpp/security/advisories/"
            "GHSA-3p4r-fq3f-q74v"
        ),
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": "418dea39cea85d3496c8b04a118c3b17f3940ad8",
        "sha256": "fd9282213a98d6fff9ce1c3a93874d92fcd0cf57727f0f07764e60763cc6cc1c",
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ArithmeticOverflow, "
            "category arithmetic): checkedAdd(tensor_data_base, cumulative "
            "aligned tensor size) overflows u64 at admission, before any "
            "downstream ggml context allocation."
        ),
        "expected_profile": "llama-cpp",
        "expected_error_code": "E_ArithmeticOverflow",
        "cli_args": ["--profile", "llama-cpp"],
    },
    {
        "name": "cve-2026-33298-ggml-nbytes-overflow.gguf",
        "fixture_type": "advisory-regression",
        "fixture_origin": "advisory-derived",
        "cve": "CVE-2026-33298",
        "ghsa": "GHSA-96jg-mvhq-q7q7",
        "bug_class": "int-overflow",
        "build": build_cve_2026_33298_nbytes_overflow,
        "source": (
            "Advisory regression (CVE-2026-33298 / GHSA-96jg-mvhq-q7q7; fix "
            "4e5b83b226919c146fbfa754641a6772bcb2d722, upstream #19072, "
            "advisory build b7824): ggml_nbytes() dimension/stride arithmetic "
            "overflow drastically underestimates tensor bytes. "
            "Advisory-derived flagship: uses the advisory's example shape F32 "
            "[1024, 1024, 2^42 + 1, 1] (element product 2^62 + 2^20 fits u64; "
            "nbytes x 4 = 2^64 + 2^22 wraps u64). Promoted from "
            "synthetic-int-overflow-flagship-nbytes.gguf with the payload "
            "unchanged; the fixture file is SafeGGUF-built, not an upstream "
            "byte copy."
        ),
        "source_url": (
            "https://github.com/ggml-org/llama.cpp/security/advisories/"
            "GHSA-96jg-mvhq-q7q7"
        ),
        "affected_range": None,
        "affected_version": None,
        "patched_version": None,
        "patched_commit": "4e5b83b226919c146fbfa754641a6772bcb2d722",
        "sha256": "dc20bf78e67fc21651278761ca10764b6a163f20a82af6790f3ff9a950e76738",
        "expected_behavior": (
            "SafeGGUF rejects (exit 2, error_code E_ArithmeticOverflow, "
            "category arithmetic): checked byte-size computation overflows u64 "
            "before allocation."
        ),
        "expected_profile": "gguf-spec",
        "expected_error_code": "E_ArithmeticOverflow",
        "cli_args": [],
    },
]

# Advisory placeholder registry: manifest-only entries for advisories whose
# primary-source provenance has not been triaged yet. Each entry would carry a
# mechanism and the expected SafeGGUF protection path, but no fixture file and
# no verified assertion; all provenance fields stay "TRIAGE-PENDING" (never
# invent tracker URLs, advisory links or commit SHAs). Promote an entry into
# CASES - and only then generate a cve-<id>-<mechanism>.gguf fixture - once
# cve, ghsa, source_url and a patched reference are recorded from a
# verifiable primary source. CVE-2025-53630, CVE-2026-27940 and CVE-2026-33298
# were promoted into CASES with triaged provenance (B3), so the registry is
# empty today; it stays available for future advisories.
ADVISORY_PLACEHOLDERS = []


# Shared schema every CASES entry must define. Provenance fields are
# nullable and stay present with a null value where nothing was verified
# (null = unknown): affected_range/affected_version/patched_version/
# patched_commit may be null individually; a cve-* case must still record at
# least one patched reference.
CASE_FIELDS = (
    "name",
    "fixture_type",
    "bug_class",
    "build",
    "source",
    "source_url",
    "affected_range",
    "affected_version",
    "patched_version",
    "patched_commit",
    "expected_behavior",
    "expected_error_code",
    "cli_args",
)

# Fields a promoted cve-* case must populate with a triaged (non-null,
# non-TRIAGE-PENDING) value: advisory identity (fixture category, closed
# fixture_origin, cve, ghsa), verifiable primary source_url, fixture sha256
# and the expected profile/error the rejection is asserted under. Version
# ranges/commits stay schema-nullable (see CASE_FIELDS). Synthetic cases
# legitimately carry null provenance (no advisory exists) and
# ADVISORY_PLACEHOLDERS stay manifest-only with TRIAGE-PENDING fields; only
# cve-* entries in CASES are held to triaged values for every field here.
REQUIRED_CVE_FIELDS = (
    "fixture_type",
    "fixture_origin",
    "cve",
    "ghsa",
    "source_url",
    "sha256",
    "expected_profile",
    "expected_error_code",
)


def _case_profile(case):
    """Effective --profile of a case (the CLI default when cli_args omit it)."""
    args = case["cli_args"]
    if "--profile" not in args:
        return "gguf-spec"
    index = args.index("--profile")
    if index + 1 >= len(args):
        return None  # dangling --profile: reported as an unknown profile
    return args[index + 1]


def _require_case_schema(case):
    """Enforce the shared case schema: known fields, all present, valid profile."""
    name = case.get("name", "<unnamed>")
    unknown = sorted(set(case) - set(CASE_FIELDS) - set(REQUIRED_CVE_FIELDS))
    if unknown:
        raise SystemExit(
            f"provenance error: {name} carries fields outside the provenance "
            f"schema: {', '.join(unknown)}"
        )
    missing = [field for field in CASE_FIELDS if field not in case]
    if missing:
        raise SystemExit(
            f"provenance error: {name} is missing schema fields: "
            f"{', '.join(missing)}"
        )
    profile = _case_profile(case)
    if profile not in PROFILES:
        raise SystemExit(
            f"provenance error: {name} uses unknown profile {profile!r} in "
            f"cli_args; expected one of {' | '.join(PROFILES)}"
        )


def _require_cve_provenance(case):
    """Enforce the full promoted cve-* provenance schema on one case."""
    name = case["name"]
    missing = [
        field
        for field in REQUIRED_CVE_FIELDS
        if not case.get(field) or case.get(field) == "TRIAGE-PENDING"
    ]
    if missing:
        raise SystemExit(
            f"provenance error: {name} claims a CVE identity without "
            f"triaged {', '.join(missing)}"
        )
    if case["fixture_type"] != "advisory-regression":
        raise SystemExit(
            f"provenance error: {name} claims a CVE identity with "
            f"fixture_type {case['fixture_type']!r} (must be "
            "'advisory-regression')"
        )
    if case["fixture_origin"] not in FIXTURE_ORIGINS:
        raise SystemExit(
            f"provenance error: {name} has fixture_origin "
            f"{case['fixture_origin']!r} outside the closed vocabulary: "
            f"{' | '.join(FIXTURE_ORIGINS)}"
        )
    if not CVE_ID_RE.match(case["cve"]):
        raise SystemExit(
            f"provenance error: {name} has malformed cve {case['cve']!r}"
        )
    if case["cve"].lower() not in name:
        raise SystemExit(
            f"provenance error: {name} cve {case['cve']} does not match the "
            "fixture name"
        )
    if not GHSA_ID_RE.match(case["ghsa"]):
        raise SystemExit(
            f"provenance error: {name} has malformed ghsa {case['ghsa']!r}"
        )
    if not case["source_url"].startswith("https://"):
        raise SystemExit(
            f"provenance error: {name} source_url is not an https URL: "
            f"{case['source_url']!r}"
        )
    if not SHA256_RE.match(case["sha256"]):
        raise SystemExit(
            f"provenance error: {name} has malformed sha256 {case['sha256']!r}"
        )
    if not (case["patched_commit"] or case["patched_version"]):
        raise SystemExit(
            f"provenance error: {name} records no patched reference "
            "(patched_commit and patched_version are both null)"
        )
    if case["expected_profile"] != _case_profile(case):
        raise SystemExit(
            f"provenance error: {name} expected_profile "
            f"{case['expected_profile']!r} does not match the cli_args profile "
            f"{_case_profile(case)!r}"
        )
    if not case["expected_error_code"].startswith("E_"):
        raise SystemExit(
            f"provenance error: {name} has malformed expected_error_code "
            f"{case['expected_error_code']!r}"
        )


def _require_triaged_provenance():
    """A cve-* fixture may only exist once its advisory provenance is triaged.

    Enforces the corpus invariant mechanically: every case fills the shared
    schema (nullable provenance fields stay present and null where unknown),
    synthetic fixtures must not borrow an advisory identity, and a cve-* case
    must satisfy the full provenance schema - triaged advisory identity,
    primary source, fixture hash, expected profile/error and a patched
    reference - with fixture_origin drawn from the closed vocabulary.
    """
    for case in CASES:
        _require_case_schema(case)
        if case["name"].startswith("cve-"):
            _require_cve_provenance(case)


def generate():
    """Deterministically write all fixtures and the manifest; prune stale files."""
    _require_triaged_provenance()
    os.makedirs(NEGATIVE_DIR, exist_ok=True)

    manifest_cases = []
    for case in CASES:
        payload = case["build"]()
        digest = hashlib.sha256(payload).hexdigest()
        declared = case.get("sha256")
        if declared is not None and declared != digest:
            raise SystemExit(
                f"provenance error: {case['name']} declares sha256 {declared} "
                f"but the generated payload hashes to {digest}"
            )
        path = os.path.join(NEGATIVE_DIR, case["name"])
        with open(path, "wb") as f:
            f.write(payload)
        manifest_cases.append(
            {
                "file": case["name"],
                "fixture_type": case["fixture_type"],
                "fixture_origin": case.get("fixture_origin"),
                "cve": case.get("cve"),
                "ghsa": case.get("ghsa"),
                "bug_class": case["bug_class"],
                "size_bytes": len(payload),
                "sha256": digest,
                "source": case["source"],
                "source_url": case["source_url"],
                "affected_range": case["affected_range"],
                "affected_version": case["affected_version"],
                "patched_version": case["patched_version"],
                "patched_commit": case["patched_commit"],
                "expected_profile": case.get("expected_profile"),
                "expected_behavior": case["expected_behavior"],
                "expected_error_code": case["expected_error_code"],
                "cli_args": ["inspect", case["name"]] + case["cli_args"],
            }
        )

    # Prune stale *.gguf files that are no longer part of CASES so the
    # directory always matches the manifest.
    keep = {case["name"] for case in CASES}
    for entry in sorted(os.listdir(NEGATIVE_DIR)):
        if entry.endswith(".gguf") and entry not in keep:
            os.remove(os.path.join(NEGATIVE_DIR, entry))

    manifest = {
        "description": (
            "Negative corpus (roadmap issue #9): synthetic bug-class exemplars "
            "+ provenance-backed advisory regressions; regenerated by "
            "tests/negative_corpus.py - do not hand-edit."
        ),
        "naming_convention": (
            "synthetic-<bug-class>-<slug>.gguf for synthetic class exemplars "
            "(no advisory identity); cve-YYYY-NNNN[-slug].gguf is reserved for "
            "triaged advisory regressions with a verifiable primary source in "
            "source_url."
        ),
        "provenance_rules": (
            "'cases' entries are generated and verified fixtures. "
            "'advisory_placeholders' are manifest-only stubs (fixture null) "
            "and must not be promoted to a cve-* fixture until cve, ghsa, "
            "source_url and a patched reference are triaged from a verifiable "
            "primary source. On promoted cve-* cases, 'fixture_origin' comes "
            "from the closed vocabulary 'exact-poc' (advisory proof of "
            "concept), 'advisory-derived' (advisory mechanism/example shape) "
            "or 'mechanism-equivalent' (equivalent admission property, not a "
            "byte-for-byte upstream reproduction); 'ghsa' carries the GHSA "
            "identifier; 'expected_profile' names the checked profile and "
            "matches the --profile in cli_args. The version/commit fields "
            "'affected_range', 'affected_version', 'patched_version' and "
            "'patched_commit' are nullable: null means not verified / unknown "
            "and is never replaced by a sentinel or an invented value. On "
            "cases without an advisory, null = no advisory provenance; "
            "TRIAGE-PENDING = explicitly unresolved."
        ),
        "upstream_behavior_reference": UPSTREAM_REF,
        "cases": manifest_cases,
        "advisory_placeholders": ADVISORY_PLACEHOLDERS,
    }
    manifest_path = os.path.join(NEGATIVE_DIR, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    return manifest_path


def run_cli(*args):
    cmd = [SAFEGGUF_BIN] + list(args)
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=10)
    return proc.returncode, proc.stdout, proc.stderr


def verify():
    """Assert every corpus fixture is rejected with exit 2 and the expected error_code."""
    failures = []
    for case in CASES:
        path = os.path.join(NEGATIVE_DIR, case["name"])
        if not os.path.exists(path):
            failures.append(f"{case['name']}: fixture missing (run generation first)")
            continue
        args = ["inspect", path] + case["cli_args"]
        try:
            rc, stdout, stderr = run_cli(*args)
        except subprocess.TimeoutExpired:
            failures.append(f"{case['name']}: CLI timed out")
            continue
        if rc != 2:
            failures.append(
                f"{case['name']}: expected exit 2 (REJECT), got {rc}\n"
                f"  stdout: {stdout.strip()}\n  stderr: {stderr.strip()}"
            )
            continue
        if case["expected_error_code"] not in stderr:
            failures.append(
                f"{case['name']}: expected error_code {case['expected_error_code']} "
                f"in stderr, got: {stderr.strip()}"
            )
            continue
        print(f"  REJECT ok [{case['bug_class']}] {case['name']} -> {case['expected_error_code']}")
    return failures


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Negative corpus: synthetic bug-class exemplars + provenance-backed "
            "advisory regressions (issue #9)"
        )
    )
    parser.add_argument("--generate-only", action="store_true", help="generate fixtures + manifest, skip verification")
    parser.add_argument("--verify-only", action="store_true", help="verify existing fixtures without regenerating")
    args = parser.parse_args()

    if not args.verify_only:
        manifest_path = generate()
        n_synthetic = sum(
            1 for c in CASES if c["fixture_type"] == "synthetic-class-exemplar"
        )
        n_advisory = sum(
            1 for c in CASES if c["fixture_type"] == "advisory-regression"
        )
        print(
            f"Generated {n_synthetic} synthetic fixtures + {n_advisory} advisory "
            f"regression fixtures + {len(ADVISORY_PLACEHOLDERS)} advisory "
            f"placeholders (manifest-only, unverified) at {manifest_path}"
        )

    if args.generate_only:
        return 0

    if not os.path.exists(SAFEGGUF_BIN):
        print(f"Error: binary {SAFEGGUF_BIN} does not exist. Run: zig build -Doptimize=ReleaseSafe")
        return 1

    print(f"Verifying {len(CASES)} negative fixtures against {SAFEGGUF_BIN} (expect exit 2 / REJECT)...")
    failures = verify()
    if failures:
        print(f"\nFAILED: {len(failures)} of {len(CASES)} cases:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1

    classes_covered = sorted({case["bug_class"] for case in CASES})
    missing_classes = [c for c in BUG_CLASSES if c not in classes_covered]
    if missing_classes:
        print(f"\nFAILED: bug classes without a sample: {missing_classes}", file=sys.stderr)
        return 1

    print(f"\nAll {len(CASES)} negative cases rejected (exit 2); bug classes covered: {classes_covered}")
    if ADVISORY_PLACEHOLDERS:
        print(
            "Advisory placeholders still TRIAGE-PENDING (manifest-only, not "
            "fixtures, not verified): "
            + ", ".join(p["id"] for p in ADVISORY_PLACEHOLDERS)
        )
    else:
        promoted = [c for c in CASES if c["fixture_type"] == "advisory-regression"]
        print(
            "No advisory placeholders remain TRIAGE-PENDING; promoted and "
            "verified advisory regressions: " + ", ".join(c["name"] for c in promoted)
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
